various improvements

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -15,14 +15,16 @@ function ynh_manually_defined_package_variables {
     #=================================================
     # VARIABLES TO DEFINE MANUALLY (REQUIRED)
     #=================================================
-    ynh_owner="Yunohost-Apps"       # YNH repo owner (it only supports GitHub for now) - e.g. "YunoHost-Apps".
-    ynh_repo="jsoncrack_ynh"        # YNH repo name - e.g. "jsoncrack_ynh".
-    upstream_branch="main"          # name of the upstream branch to get the source from - often "main".
-    source_type="commit"            # "commit" or "release", depending on whether you want the build script to build the source based on the latest commit or on the latest release.
-    default_build_folder="out"      # the folder where to find the built files after build - often "dist".
-    framework="nodejs"              # framework that should be installed - currently only "nodejs" or "none" are supported.
-    build_nodejs_version=20         # NodeJS version to use (if any) for the build.
-    gh_personal_token=""            # [local build only] fill with your GitHub Personal Token if you want to upload the release to GitHub after build - cf. https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
+    ynh_owner="Yunohost-Apps"           # YNH repo owner (it only supports GitHub for now) - e.g. "YunoHost-Apps".
+    ynh_repo="jsoncrack_ynh"            # YNH repo name - e.g. "jsoncrack_ynh".
+    upstream_version_source="manifest"  # "manifest" or "latest", will pick the source archive's URL either with the version defined in the manifest.toml or the latest version available at upstream repo.  
+    upstream_branch_name="main"         # name of the upstream branch to get the source from - often "main" or "master".
+    default_build_folder="out"          # the folder where to find the built files after build - often "dist".
+    framework="nodejs"                  # framework that should be installed - currently only "nodejs" or "none" are supported.
+    build_nodejs_version=20             # NodeJS version to use (if any) for the build.
+    
+    # Local build only
+    gh_personal_token=""                # fill with your GitHub Personal Token if you want to upload the release to GitHub after build - cf. https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
 }
 
 function ynh_optional_source_customizations {
@@ -108,8 +110,12 @@ function used_disk_space_in_gb {
   echo $output
 }
 
+#=================================================
+# INITIATE
+#=================================================
 # Start tracing for debug output
 set -x
+
 storage_start=$(used_disk_space_in_gb)
 
 #=================================================
@@ -122,28 +128,70 @@ ynh_manually_defined_package_variables
 # Parse manifest automatically
 curl --silent --output ynh-manifest.toml "https://raw.githubusercontent.com/${ynh_owner}/${ynh_repo}/refs/heads/master/manifest.toml"
 upstream_url="$(grep -A 5 'resources.sources.main' ynh-manifest.toml | grep url | grep -o 'http[s]\?://[^ "]\+' | head -1)"
-upstream_owner="$(echo $upstream_url | cut -d/ -f4)"
-upstream_repo="$(echo $upstream_url | cut -d/ -f5)"
 rm ynh-manifest.toml
 
+# Check that required variables are defined
+required_vars=(ynh_owner ynh_repo upstream_version_source upstream_branch_name  default_build_folder framework upstream_url)
+for var_name in "${required_vars[@]}"; do
+    [ -z "${!var_name}" ] && echo "required $var_name is unset." && required_var_unset=true
+done
+if [ -n "$required_var_unset" ]; then
+    echo "Error - one or more required variables are unset. Please make sure that all required variable are defined in the build script's \"SECTION TO EDIT\" and in the associated resources of the manifest.toml."
+    exit 1
+fi
 #=================================================
 # DOWNLOAD AND EXTRACT SOURCE
 #=================================================
-full_upstream_path="${upstream_owner}/${upstream_repo}"
-if [[ $source_type == "release" ]]; then
-    last_upstream_version=$(curl --silent "https://api.github.com/repos/${full_upstream_path}/releases/latest" | grep -Po "(?<=\"tag_name\": \").*(?=\")") #e.g. v3.2.0 (but format is manually defined by repo upstream authors and could be anything)
-    download_url="https://api.github.com/repos/${full_upstream_path}/tarball/${last_upstream_version}"
-    build_folder="${upstream_repo}_${last_upstream_version}" #e.g. jsoncrack.com_v3.2.0
-    release_version="${last_upstream_version}"
-else
-    last_upstream_version=$(curl --silent "https://api.github.com/repos/${full_upstream_path}/commits/${upstream_branch}" | grep -Po "(?<=\"sha\": \").*(?=\")" | head -n 1) #e.g. d5f9bfc7fba1f1908863390f16ba28589d84a7d5
-    last_upstream_version_short=${last_upstream_version:0:8}
-    last_date_tag=$(curl --silent "https://api.github.com/repos/${full_upstream_path}/commits/${upstream_branch}" | grep -Po "(?<=\"verified_at\": \").*(?=\")" | head -n 1) #e.g. 2024-11-19T18:37:03Z
-    last_date_tag_short=$(echo ${last_date_tag:0:10} | sed 's/-/./g') #e.g. 2024.11.19
-    download_url="https://github.com/${full_upstream_path}/archive/${last_upstream_version}.tar.gz"
-    build_folder="${upstream_repo}_v${last_date_tag_short}-${last_upstream_version_short}" #e.g. jsoncrack.com_v2024.11.19-d5f9bfc7
-    release_version="${build_folder#${upstream_repo}_}"
-fi
+# Parse URL (GitHub)
+github_url_regex="^https://(api.)?github.com/(repos/)?([a-zA-Z0-9._-]*)/([a-zA-Z0-9._-]*)/(releases|archive)?/(refs/tags/|download/)?([a-zA-Z0-9._-]*).*$"
+if [[ "$upstream_url" =~ $github_url_regex ]]; then
+    upstream_owner="${BASH_REMATCH[3]}"
+    upstream_repo"${BASH_REMATCH[4]}"
+    upstream_source_type="${BASH_REMATCH[6]}"
+    upstream_tag="${BASH_REMATCH[7]}"
+
+    full_upstream_path="${upstream_owner}/${upstream_repo}"
+
+    if [[ $upstream_source_type == *"download"* ]]; then
+        upstream_source_type="release"
+        if [[ "$upstream_version_source" == "latest" ]]; then
+            upstream_releases_json_url="https://api.github.com/repos/${full_upstream_path}/releases"
+            upstream_tag=$(curl --silent "$upstream_releases_json_url" | | jq '.[] | select(( .prerelease == false ) and ( .draft == false )) | .tag_name') | head -n 1 #e.g. v3.2.0 (but format is manually defined by repo upstream authors and could be anything)
+            download_url="https://api.github.com/repos/${full_upstream_path}/tarball/${upstream_tag}"
+        fi
+        build_folder="${upstream_repo}_${upstream_tag}" #e.g. jsoncrack.com_v3.2.0
+        release_version="${upstream_tag}"
+
+    elif [[ $upstream_source_type == *"tags"* ]]; then
+        upstream_source_type="tag"
+        if [[ "$upstream_version_source" == "latest" ]]; then
+            upstream_tags_json_url="https://api.github.com/repos/${full_upstream_path}/tags"
+            upstream_tag=$(curl --silent "$upstream_tags_json_url" | grep -Po "(?<=\"tag_name\": \").*(?=\")") #e.g. v3.2.0 (but format is manually defined by repo upstream authors and could be anything)
+            download_url="https://api.github.com/repos/${full_upstream_path}/tarball/refs/tags/${upstream_tag}"
+        fi
+        build_folder="${upstream_repo}_${upstream_tag}" #e.g. jsoncrack.com_v3.2.0
+        release_version="${upstream_tag}"
+
+    else
+        upstream_source_type="commit"
+        if [[ "$upstream_version_source" == "latest" ]]; then
+            latest_upstream_commit_json_url="https://api.github.com/repos/${full_upstream_path}/commits/${upstream_branch_name}"
+            upstream_tag=$(curl --silent "$latest_upstream_commit_json_url" | grep -Po "(?<=\"sha\": \").*(?=\")" | head -n 1) #e.g. d5f9bfc7fba1f1908863390f16ba28589d84a7d5
+            upstream_tag_short=${upstream_tag:0:8}
+            last_date_tag=$(curl --silent "$latest_upstream_commit_json_url" | grep -Po "(?<=\"verified_at\": \").*(?=\")" | head -n 1) #e.g. 2024-11-19T18:37:03Z
+            last_date_tag_short=$(echo ${last_date_tag:0:10} | sed 's/-/./g') #e.g. 2024.11.19
+            download_url="https://github.com/${full_upstream_path}/archive/${upstream_tag}.tar.gz"
+        fi
+        build_folder="${upstream_repo}_v${last_date_tag_short}-${upstream_tag_short}" #e.g. jsoncrack.com_v2024.11.19-d5f9bfc7
+        release_version="${build_folder#${upstream_repo}_}"
+    fi
+    
+else 
+    echo "Error - Wrong GitHub URL supplied"
+    exit 1
+fi 
+
+# Download and extract source
 curl -LJ $download_url --output "${build_folder}.tar.gz"
 mkdir "$build_folder"
 tar --strip-components=1 -xvf "${build_folder}.tar.gz" -C "./${build_folder}/"
@@ -152,7 +200,7 @@ storage_extract_source=$(used_disk_space_in_gb)
 #=================================================
 # SOURCE CUSTOMIZATION
 #=================================================
-# Optional source customizations @MANUAL FILL 
+# Optional source customizations
 pushd "$build_folder"
     # Execute source customizations commands (if any)
     ynh_optional_source_customizations
@@ -171,7 +219,7 @@ if [ "$framework" = "nodejs" ] && [ "$current_node_version" != "$build_nodejs_ve
         curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash #Official install script from https://github.com/nvm-sh/nvm#install--update-script
     fi
     
-    # Instlal required NodeJS version 
+    # Install required NodeJS version 
     source ~/.nvm/nvm.sh install $build_nodejs_version
 fi
 
@@ -194,7 +242,7 @@ pushd "$build_folder"
 popd
 ynh_release_SHA=$(sha256sum ${ynh_release_filename} | cut -d' ' -f1)
 ynh_release_URL="https://github.com/${ynh_owner}/${ynh_repo}/releases/download/${release_version}/${ynh_release_filename}"
-ynh_release_version="${release_version#${upstream_repo}_}" #e.g. v3.2.0 (release source) OR v2024.11.19-d5f9bfc7 (commit source)
+ynh_release_version="${release_version#${upstream_repo}_}" #e.g. v3.2.0 (release/tag source) OR v2024.11.19-d5f9bfc7 (commit source)
 storage_end=$(used_disk_space_in_gb)
 
 # Compute disk usage statistics
@@ -207,31 +255,31 @@ rm -r "${build_folder}"
 rm "${build_folder}.tar.gz"
 
 #=================================================
-# GENERATE CHANGELOG URL (COMMITS HISTORY)
+# GENERATE CHANGELOG URL
 #=================================================
-# Get previous commit SHA-1 string
-previous_upstream_filename=${upstream_url##*/}
-previous_upstream_filename=${previous_upstream_filename%.tar.gz}
-previous_upstream_filename=${previous_upstream_filename%.zip}
-if [[ "$previous_upstream_filename" =~ ^[0-9a-f]{40}$ ]] #check if filename is a SHA-1 string or a tag
-then 
-previous_release_commit_SHA_full=${previous_upstream_filename}
-else
-previous_release_commit_SHA_full=$(curl --silent "https://api.github.com/repos/${full_upstream_path}/git/refs/tags/" | jq -r ".[] | select(.ref==\"refs/tags/${previous_upstream_filename}\") | .object.sha") 
-fi
-previous_release_commit_SHA_short=${previous_release_commit_SHA_full:0:8}
+if [[ "$upstream_source_type" == "commit" ]]; then #build diff URL (commits history)
 
-# Get current commit SHA-1 string
-if [[ "$ynh_release_version" =~ ^v[0-9]{4}\.[0-9]{2}\.[0-9]{2}-[0-9a-f]{8}$ ]] #check if it has commit (predictable) or release (unpredictable) format.
-then
-current_release_commit_SHA_short=${ynh_release_version##*-}
-else
-current_release_commit_SHA_full=$(curl --silent "https://api.github.com/repos/${full_upstream_path}/git/refs/tags/" | jq -r ".[] | select(.ref==\"refs/tags/${ynh_release_version}\") | .object.sha") 
-current_release_commit_SHA_short=${current_release_commit_SHA_full:0:8}
-fi
+    # Get previous commit SHA-1 string
+    if [[ "$upstream_version_source" == "latest" ]]; then #history between current manifest and last upstream commit  
+        previous_upstream_filename=${upstream_url##*/}
+        previous_upstream_filename=${previous_upstream_filename%.tar.gz}
+        previous_upstream_filename=${previous_upstream_filename%.zip}
+        previous_release_commit_SHA_short=${previous_release_commit_SHA_full:0:8}        
+    else #history between previous manifest and current manifest
+        ynh_releases_json_url="https://api.github.com/repos/${ynh_owner}/${ynh_repo}/releases"
+        previous_upstream_filename=$(curl --silent "$ynh_releases_json_url" | jq '.[] | select(( .prerelease == false ) and ( .draft == false )) | .tag_name') | head -n 2 | tail -n 1 #e.g. v2025.05.01-9f801cd6
+        previous_release_commit_SHA_short=${previous_upstream_filename: -8}
+    fi
 
-# Create final URL
-ynh_release_diff_url="https://github.com/${full_upstream_path}/compare/${previous_release_commit_SHA_short}...${current_release_commit_SHA_short}"
+    # Get current commit SHA-1 string
+    current_release_commit_SHA_short=${ynh_release_version: -8}
+
+    # Create diff URL
+    ynh_release_changelog_url="https://github.com/${full_upstream_path}/compare/${previous_release_commit_SHA_short}...${current_release_commit_SHA_short}"
+
+else #show upstream's release page
+    ynh_release_changelog_url="https://github.com/${full_upstream_path}/releases/tag/${upstream_tag}"
+fi
 
 #=================================================
 # UPLOAD RELEASE (LOCAL BUILD ONLY)
@@ -242,7 +290,7 @@ if [[ $gh_personal_token && -z $GITHUB_OUTPUT ]]; then
 
     if [[ "$@" =~ "push_release" ]]; then
         ## Make a draft release json with a markdown body
-        release='"tag_name": "'$last_upstream_version'", "target_commitish": "master", "name": "'$last_upstream_version'", '
+        release='"tag_name": "'$upstream_tag'", "target_commitish": "master", "name": "'$upstream_tag'", '
         body="${upstream_repo^} prebuilt archive for ${ynh_repo}\\n=========\\nPlease refer to upstream ${upstream_repo^} project for the change : https://github.com/$full_upstream_path/releases\\n\\nSha256sum : $ynh_release_SHA"
         body=\"$body\"
         body='"body": '$body', '
@@ -318,7 +366,7 @@ if [[ $GITHUB_OUTPUT ]]; then
     echo "YNH_RELEASE_SHA=${ynh_release_SHA}" >> $GITHUB_OUTPUT
     echo "YNH_RELEASE_URL=${ynh_release_URL}" >> $GITHUB_OUTPUT
     echo "YNH_RELEASE_VERSION=${ynh_release_version}" >> $GITHUB_OUTPUT
-    echo "YNH_RELEASE_DIFF_COMPARE_URL=${ynh_release_diff_url}" >> $GITHUB_OUTPUT
+    echo "YNH_RELEASE_CHANGELOG_URL=${ynh_release_changelog_url}" >> $GITHUB_OUTPUT
     echo "BUILD_STORAGE_USE=${total_storage_used}" >> $GITHUB_OUTPUT
     echo "BUILD_STORAGE_USE_EXCL_FRAMEWORK=${total_storage_used_without_framework}" >> $GITHUB_OUTPUT
     
